package com.generation.personalblog.model;

import java.time.LocalDateTime;

import org.hibernate.annotations.UpdateTimestamp;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

//this class defines an entity
@Entity 
//creates the table and defines its name
@Table(name = "tb_posts")
public class Posts {
	
	//indicates that the attribute will be the PK for tb_posts
	@Id
	//indicates that the PK will be generated by the db and GenerationType.IDENTITY indicates that it'll be auto incremented
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	@NotBlank(message = "The attribute title is mandatory!")
	@Size(min = 5, max = 100, message = "The attribute title must have at least 5 characters and a maximum of 100.")
	private String title;
	
	@NotBlank(message = "The attribute text is mandatory!")
	@Size(min = 10, max = 1000, message = "The attribute title must have at least 10 characters and a maximum of 1000.")
	private String text;
	
	@UpdateTimestamp
	private LocalDateTime date;
	
	@ManyToOne
	@JsonIgnoreProperties("posts")
	private Theme theme;
	
	@ManyToOne
	@JsonIgnoreProperties("posts")
	private User user;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public LocalDateTime getDate() {
		return date;
	}

	public void setDate(LocalDateTime date) {
		this.date = date;
	}

	public Theme getTheme() {
		return theme;
	}

	public void setTheme(Theme theme) {
		this.theme = theme;
	}

}
